export const homeUrl = "/"
export const usersUrl = "/users"
export const profileUrl = "/users/:id"
export const postsUrl = "/posts"
export const loginUrl = "/login"
export const registerUrl = "/register"
export const addPostUrl = "/add-post"
